apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yeti.fullname" . }}
  labels:
  {{- include "yeti.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    in_cluster: true

    server:  # the server config section
      enable_https: false  # if the yeti is deployed as an https server, set it to true
      port: 7777  # the server port
      migration_dir: /app/db/migrations  # the migrations sql files directory

    {{- (ternary "" (toYaml .Values.configFileContent) (empty .Values.configFileContent)) | nindent 4 }}
